sonar.projectKey=Bahmni_openmrs-module-appointments
sonar.organization=bahmni
sonar.projectName=openmrs-module-appointments

sonar.sources=api/src/main/java,atom-feed/src/main/java,omod/src/main/java
sonar.tests=api/src/test/java,atom-feed/src/test/java,omod/src/test/java
sonar.java.binaries=api/target/classes,atom-feed/target/classes,omod/target/classes

sonar.coverage.jacoco.xmlReportPaths=api/target/site/jacoco/jacoco.xml,atom-feed/target/site/jacoco/jacoco.xml,omod/target/site/jacoco/jacoco.xml

sonar.coverage.exclusions=**/*Test.java,**/*IT.java

sonar.sourceEncoding=UTF-8
